export const LORE_QUOTES = [
  "I'm going to invite you mom on my honeymoon. Maybe not dad. I'll talk to my wife about it.",
  'Boomy fell down the stairs just like he did this morning. But he did it when he was working as a cleaning person at school.',
  'Callie fell up the stairs one time.',
  'The baddest truck in all the land has lasers and horns, and took over the entire truck world.',
  "Know what GL's password is? 41 Muffin Lane.",
  'Grandpa Logger is scared of wearing shoes. They might have claws that wrap you up.',
  'When Grandpa Logger was a teenager he worked for Ice Age looking for saber tooth tigers.',
  'Grandpa Logger parents are secret agents (like Spiderman).',
  'Brother, the brother of Grandpa Logger, has a grappling arm with spikes on it.',
  'Boomy sleeps in a cage and so do trucks, but sometimes Boomy sleeps on the rotten roof of an old building.',
  'Callie sleeps in the sand around a cement mixer and Grandpa Logger sleeps on his logging bed after he cleans it.',
  "Grandpa Logger's son is named Storm Wolverine Cyclops.",
  'Grandpa Logger loves corn ice cream and sour cream ice cream.',
  'When will I have big private business?',
  'If I have 10 fingers, Grandpa Logger has 10 basements.',
  "Dad, I'm kind of sad. I can't talk to trucks anymore. I have to not listen to them and get rid of them.",
  'The only person in my imagination I can talk to now is Ash Ketchum.',
  "I need to tell you a fact about penguins. The mommy throws up into the daddy and that's how a baby is made.",
  'I wish Jesus was still alive so I could give him flowers and make him a peanut butter and jelly sandwich.',
  'Mommaaaaaaa? My this tooth hurts, and my uppercase tooth hurts.',
  'I need to be evaluated by a doctor to figure out how I can run faster than a racecar.',
  'You absolutely can regrow your nuts dad. The other day I got hit in the nuts and the next morning I woke up with two new nuts. And two nuts the next day.',
  'How fast is a timber rattlesnake? I bet they could not outrun an obstacle course.',
] as const

export const CHARACTERS = [
  'Dan',
  'Kara',
  'Cade',
  'Bowen',
  'Callie',
  'Grandpa Logger',
  'Brother',
  'Storm Wolverine Cyclops',
  'Boomy',
] as const
